# -*- coding: utf-8 -*-
"""valid_identifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W1R5bd9lxA2j6gmLKgc9Y9-1-nDQOu4e
"""

import re

def is_valid_identifier(identifier):
    # Regular expression to check if the identifier is valid
    pattern = r'^[a-zA-Z_][a-zA-Z0-9_]*$'
    return re.match(pattern, identifier) is not None

# Input identifier to validate
identifier = input("Enter an identifier: ")

if is_valid_identifier(identifier):
    print(f"{identifier} is a valid identifier.")
else:
    print(f"{identifier} is not a valid identifier.")